version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  user_app:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
